// <auto-generated />
using System;
using BleApi.Orders.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BleApi.Orders.Migrations
{
    [DbContext(typeof(OrdersDbContext))]
    partial class OrdersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.9");

            modelBuilder.Entity("BleApi.Orders.Model.Orders", b =>
                {
                    b.Property<int>("order_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("order_date")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("order_image")
                        .HasColumnType("BLOB");

                    b.Property<string>("order_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("order_id");

                    b.ToTable("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
