// <auto-generated />
using System;
using BleApi.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BleApi.Migrations
{
    [DbContext(typeof(BleDbContext))]
    [Migration("20220907112904_Ble")]
    partial class Ble
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.8");

            modelBuilder.Entity("BleApi.Model.Orders", b =>
                {
                    b.Property<int>("order_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("order_date")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("order_image")
                        .HasColumnType("BLOB");

                    b.Property<string>("order_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("order_id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("BleApi.Model.Products", b =>
                {
                    b.Property<int>("product_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("procuct_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("product_image")
                        .HasColumnType("BLOB");

                    b.Property<double>("product_price")
                        .HasColumnType("REAL");

                    b.Property<int>("product_stock")
                        .HasColumnType("INTEGER");

                    b.Property<int>("provider_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("product_id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("BleApi.Model.Providers", b =>
                {
                    b.Property<int>("provider_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("order_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("provider_mail")
                        .HasColumnType("TEXT");

                    b.Property<string>("provider_name")
                        .HasColumnType("TEXT");

                    b.Property<string>("provider_phone")
                        .HasColumnType("TEXT");

                    b.HasKey("provider_id");

                    b.ToTable("Providers");
                });
#pragma warning restore 612, 618
        }
    }
}
