// <auto-generated />
using BleApi.Providers.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BleApi.Providers.Migrations
{
    [DbContext(typeof(ProvidersDbContext))]
    partial class ProvidersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.9");

            modelBuilder.Entity("BleApi.Providers.Model.Providers", b =>
                {
                    b.Property<int>("provider_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("order_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("provider_mail")
                        .HasColumnType("TEXT");

                    b.Property<string>("provider_name")
                        .HasColumnType("TEXT");

                    b.Property<string>("provider_phone")
                        .HasColumnType("TEXT");

                    b.HasKey("provider_id");

                    b.ToTable("Providers");
                });
#pragma warning restore 612, 618
        }
    }
}
